name: WPF Syntax Check

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install .NET Framework 4.7.2
      run: |
        choco install dotnet-472-devpack --yes --force
        RefreshEnv.cmd

    - name: Install StyleCop.MSBuild
      run: nuget install StyleCop.MSBuild -Version 6.1.0 -OutputDirectory packages

    - name: Restore NuGet packages
      run: msbuild /t:Restore SocailNetSchool.sln

    - name: Build solution
      run: msbuild /t:Build /p:Configuration=Release /p:Platform="Any CPU" SocailNetSchool.sln

    - name: Run StyleCop
      run: msbuild /t:StyleCop SocailNetSchool.sln